# Generated by Django 3.2.5 on 2022-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221120_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
