# Generated by Django 3.2.5 on 2022-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_end_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_counter',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
