# Generated by Django 3.2.5 on 2022-11-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221120_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login_date',
        ),
    ]
