# Generated by Django 3.2.5 on 2022-11-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_first_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
