# Generated by Django 3.2.5 on 2022-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlang',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
