version: "3"

services:
  api:
    expose:
      - "8000"
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    networks:
      - ohealth-backend-tier
    environment:
     - NGINX_HOST=www.oral.lxc
     - NGINX_PORT=80
