# Generated by Django 3.2.5 on 2023-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_connection_if_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='if_active',
            new_name='is_active',
        ),
    ]
