# Generated by Django 3.2.5 on 2023-03-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
    ]
