# Generated by Django 3.2.5 on 2023-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_companylang_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='request_type',
            field=models.CharField(blank=True, choices=[('DOCTOR_REQUEST', 'DOCTOR_REQUEST'), ('DOCTOR_APPROVAL', 'DOCTOR_APPROVAL'), ('OWNER_REQUEST', 'OWNER_REQUEST'), ('OWNER_APPROVAL', 'OWNER_APPROVAL'), ('PATIENT_REQUEST_DOCTOR', 'PATIENT_REQUEST_DOCTOR'), ('DOCTOR_REQUEST_PATIENT', 'DOCTOR_REQUEST_PATIENT'), ('DOCTOR_ACCEPT_PATIENT_REQUEST', 'DOCTOR_ACCEPT_PATIENT_REQUEST'), ('PATIENT_ACCEPT_DOCTOR_REQUEST', 'PATIENT_ACCEPT_DOCTOR_REQUEST'), ('DOCTOR_REVOKE_PATIENT_ACCESS', 'DOCTOR_REVOKE_PATIENT_ACCESS'), ('PATIENT_REVOKE_DOCTOR_ACCESS', 'PATIENT_REVOKE_DOCTOR_ACCESS')], max_length=255, null=True, verbose_name='Request Type'),
        ),
    ]
