# Generated by Django 3.2.5 on 2023-03-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userlang_gender'),
        ('common', '0003_alter_companyuser_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcode',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.multilanguage'),
        ),
    ]
