# Generated by Django 3.2.5 on 2023-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_appointmentcode_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticlang',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentlang',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
